/** Styles for the admin Docker management panel — dark theme matching Chat. */

export const adminStyles: Record<string, React.CSSProperties> = {
  container: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "#0f1117",
    color: "#e4e4e7",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    overflow: "hidden",
  },

  // --- Header ------------------------------------------------------------
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    borderBottom: "1px solid #2a2d3a",
    background: "#1a1b26",
    flexShrink: 0,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  headerIcon: { fontSize: "22px" },
  headerTitle: { fontSize: "17px", fontWeight: 600, color: "#e4e4e7" },
  headerSubtitle: { fontSize: "12px", color: "#71717a" },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  whoami: { fontSize: "13px", color: "#a1a1aa" },

  // --- Buttons -----------------------------------------------------------
  btn: {
    padding: "6px 14px",
    border: "1px solid #2a2d3a",
    background: "#1a1b26",
    color: "#d4d4d8",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
  },
  btnPrimary: {
    padding: "6px 14px",
    border: "none",
    background: "#6366f1",
    color: "#fff",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
  },
  btnDanger: {
    padding: "6px 14px",
    border: "1px solid #7f1d1d",
    background: "#2a1215",
    color: "#f87171",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
  },
  btnSmall: {
    padding: "4px 10px",
    border: "1px solid #2a2d3a",
    background: "#1a1b26",
    color: "#d4d4d8",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  btnSmallDanger: {
    padding: "4px 10px",
    border: "1px solid #7f1d1d",
    background: "#2a1215",
    color: "#f87171",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  btnSmallWarn: {
    padding: "4px 10px",
    border: "1px solid #713f12",
    background: "#27200d",
    color: "#fbbf24",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  btnDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },

  // --- Body / overview cards ---------------------------------------------
  body: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  cardsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "12px",
    flexShrink: 0,
  },
  card: {
    background: "#1a1b26",
    border: "1px solid #2a2d3a",
    borderRadius: "10px",
    padding: "14px 16px",
  },
  cardLabel: { fontSize: "12px", color: "#71717a", marginBottom: "6px" },
  cardValue: { fontSize: "24px", fontWeight: 700, color: "#e4e4e7" },
  cardValueGreen: { fontSize: "24px", fontWeight: 700, color: "#22c55e" },
  cardValueRed: { fontSize: "24px", fontWeight: 700, color: "#ef4444" },
  cardSub: { fontSize: "11px", color: "#52525b", marginTop: "4px" },

  // --- Table -------------------------------------------------------------
  tableWrap: {
    background: "#1a1b26",
    border: "1px solid #2a2d3a",
    borderRadius: "10px",
    overflow: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
    minWidth: "980px",
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    color: "#71717a",
    fontWeight: 600,
    fontSize: "12px",
    borderBottom: "1px solid #2a2d3a",
    position: "sticky" as const,
    top: 0,
    background: "#1a1b26",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "10px 12px",
    borderBottom: "1px solid #232634",
    verticalAlign: "top",
    whiteSpace: "nowrap",
  },
  tdWrap: {
    padding: "10px 12px",
    borderBottom: "1px solid #232634",
    verticalAlign: "top",
    whiteSpace: "normal",
    wordBreak: "break-all",
    maxWidth: "260px",
  },
  userCell: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  avatar: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    background: "#6366f1",
    color: "#fff",
    fontSize: "11px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  muted: { color: "#71717a" },
  mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace", fontSize: "12px" },

  // --- Status badges -------------------------------------------------------
  badge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 600,
    lineHeight: "16px",
  },
  badgeGreen: { background: "#052e16", color: "#4ade80", border: "1px solid #14532d" },
  badgeYellow: { background: "#27200d", color: "#fbbf24", border: "1px solid #713f12" },
  badgeRed: { background: "#2a1215", color: "#f87171", border: "1px solid #7f1d1d" },
  badgeGray: { background: "#1f2029", color: "#a1a1aa", border: "1px solid #2a2d3a" },
  badgeBlue: { background: "#172554", color: "#93c5fd", border: "1px solid #1e3a8a" },

  // --- Modal (logs & destroy confirm) -------------------------------------
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "24px",
  },
  modal: {
    background: "#1a1b26",
    border: "1px solid #2a2d3a",
    borderRadius: "12px",
    width: "min(900px, 100%)",
    maxHeight: "85vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    borderBottom: "1px solid #2a2d3a",
    gap: "10px",
  },
  modalTitle: { fontSize: "14px", fontWeight: 600 },
  modalBody: { padding: "16px 18px", overflowY: "auto", fontSize: "13px" },
  logBox: {
    background: "#0d0f14",
    border: "1px solid #232634",
    borderRadius: "8px",
    padding: "12px",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    fontSize: "12px",
    lineHeight: 1.55,
    color: "#c9cdd6",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    minHeight: "200px",
    maxHeight: "58vh",
    overflowY: "auto",
    margin: 0,
  },
  modalFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "10px",
    padding: "12px 18px",
    borderTop: "1px solid #2a2d3a",
  },
  select: {
    padding: "5px 8px",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    background: "#0f1117",
    color: "#d4d4d8",
    fontSize: "12px",
    cursor: "pointer",
  },
  input: {
    padding: "8px 12px",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    background: "#0f1117",
    color: "#e4e4e7",
    fontSize: "13px",
    outline: "none",
    width: "100%",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  },
  warnText: {
    color: "#fbbf24",
    fontSize: "13px",
    lineHeight: 1.6,
    marginBottom: "12px",
  },

  // --- Toast & misc --------------------------------------------------------
  toast: {
    position: "fixed",
    bottom: "28px",
    left: "50%",
    transform: "translateX(-50%)",
    background: "#1a1b26",
    border: "1px solid #2a2d3a",
    color: "#e4e4e7",
    padding: "10px 18px",
    borderRadius: "8px",
    fontSize: "13px",
    boxShadow: "0 8px 30px rgba(0,0,0,0.45)",
    zIndex: 1100,
  },
  errorBanner: {
    background: "#2a1215",
    border: "1px solid #7f1d1d",
    color: "#f87171",
    borderRadius: "8px",
    padding: "10px 14px",
    fontSize: "13px",
  },
  empty: {
    textAlign: "center",
    color: "#52525b",
    padding: "40px 0",
    fontSize: "13px",
  },
  actionsCell: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "#a1a1aa",
    cursor: "pointer",
    userSelect: "none",
  },
};
