import type { CSSProperties } from "react";

/**
 * Light, clean, minimal theme inspired by opencode's own web frontend.
 *
 * Palette (opencode light tokens, softened):
 *   page bg        #f7f8fa
 *   surface/card   #ffffff
 *   subtle fill    #f1f3f5
 *   border         #e6e8ee
 *   text primary   #16181d
 *   text secondary #5b6472
 *   text muted     #9aa2b1
 *   accent         #2563eb
 */

export const layerColors: Record<string, string> = {
  browser: "#3b82f6",
  platform: "#8b5cf6",
  container: "#06b6d4",
  shared: "#10b981",
};

const toolColors: Record<string, string> = {
  pending: "#9aa2b1",
  running: "#f59e0b",
  completed: "#16a34a",
  error: "#dc2626",
};

// Shared tokens -------------------------------------------------------------
const border = "#e6e8ee";
const borderStrong = "#d5dae3";
const surface = "#ffffff";
const subtle = "#f1f3f5";
const page = "#f7f8fa";
const text = "#16181d";
const textSec = "#5b6472";
const textMut = "#9aa2b1";
const accent = "#2563eb";
const accentSoft = "rgba(37,99,235,0.08)";

/** `any` because a few entries are style factories, not plain CSSProperties. */
export const styles: Record<string, any> = {
  container: { display: "flex", height: "100vh", background: page, color: text },
  sidebar: {
    width: "300px",
    borderRight: `1px solid ${border}`,
    display: "flex",
    flexDirection: "column",
    background: surface,
  },
  sidebarHeader: { padding: "16px", borderBottom: `1px solid ${border}` },
  brand: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "12px" },
  brandIcon: { fontSize: "20px" },
  brandText: { fontSize: "16px", fontWeight: 600, color: text },
  userInfo: { display: "flex", alignItems: "center", gap: "8px" },
  userAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    background: accent,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: 600,
    color: "#fff",
  },
  userName: { flex: 1, fontSize: "13px", color: textSec },
  logoutBtn: {
    background: "none",
    border: `1px solid ${border}`,
    color: textSec,
    padding: "4px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "12px",
  },
  statusPanel: { padding: "16px", borderBottom: `1px solid ${border}` },
  statusRow: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" },
  statusDot: { width: "8px", height: "8px", borderRadius: "50%" },
  statusText: { fontSize: "14px", fontWeight: 500, color: text },
  containerName: {
    fontSize: "12px",
    color: textSec,
    marginBottom: "4px",
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusDetail: { fontSize: "11px", color: textMut, marginBottom: "10px" },
  runtimeBox: {
    fontSize: "11px",
    color: textMut,
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "8px",
    marginBottom: "10px",
    lineHeight: 1.6,
  },
  runtimeKey: { color: textSec },
  runtimeVal: { color: text, fontFamily: "monospace" },
  statusButtons: { display: "flex", gap: "8px" },
  startBtn: {
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "8px",
    background: "#16a34a",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  stopBtn: {
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "8px",
    background: "#dc2626",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  logBtn: {
    padding: "8px 12px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: surface,
    color: textSec,
    fontSize: "13px",
    cursor: "pointer",
  },
  sessionsSection: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  sessionsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    fontSize: "13px",
    color: textSec,
    fontWeight: 500,
  },
  newSessionBtn: {
    width: "24px",
    height: "24px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    background: surface,
    color: textSec,
    fontSize: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sessionsList: { flex: 1, overflowY: "auto", padding: "0 8px" },
  emptySessions: { padding: "16px", fontSize: "12px", color: textMut, textAlign: "center" },
  sessionItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    color: textSec,
  },
  sessionItemActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    color: text,
    background: accentSoft,
  },
  sessionIcon: { fontSize: "14px" },
  sessionTitle: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionItemActiveTitle: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionActions: { display: "flex", gap: "4px", marginLeft: "auto", flexShrink: 0 },
  sessionActionBtn: {
    width: "20px",
    height: "20px",
    border: "none",
    borderRadius: "4px",
    background: "transparent",
    color: textMut,
    fontSize: "11px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },

  // --- permission / question approval cards ---
  permCard: {
    background: "#fffbeb",
    border: "1px solid #fcd34d",
    borderRadius: "10px",
    padding: "12px 16px",
    marginBottom: "12px",
  },
  permTitle: { fontSize: "13px", fontWeight: 600, color: "#b45309", marginBottom: "6px" },
  permRes: {
    fontSize: "12px",
    color: textSec,
    fontFamily: "monospace",
    background: "#fff",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    padding: "4px 8px",
    marginBottom: "4px",
    wordBreak: "break-all",
  },
  // P1-5: pretty-printed tool input arguments on the approval card.
  permMeta: {
    margin: "8px 0 0",
    padding: "8px 10px",
    background: "#fff",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    fontSize: "11px",
    color: textSec,
    fontFamily: "monospace",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: "200px",
    overflowY: "auto",
  },
  permActions: { display: "flex", gap: "8px", marginTop: "10px" },
  permAllowBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    background: "#16a34a",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  permAlwaysBtn: {
    padding: "6px 12px",
    border: "1px solid #16a34a",
    borderRadius: "6px",
    background: "transparent",
    color: "#16a34a",
    fontSize: "12px",
    cursor: "pointer",
  },
  permRejectBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    background: "#dc2626",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  quesCard: {
    background: "#eef2ff",
    border: "1px solid #c7d2fe",
    borderRadius: "10px",
    padding: "12px 16px",
    marginBottom: "12px",
  },
  quesTitle: { fontSize: "13px", fontWeight: 600, color: "#4338ca", marginBottom: "8px" },
  quesQuestion: { fontSize: "13px", color: text, marginBottom: "4px" },
  quesOptions: { display: "flex", flexDirection: "column", gap: "4px", marginBottom: "8px" },
  quesOption: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    fontSize: "12px",
    color: textSec,
    cursor: "pointer",
  },
  quesOptionLabel: { color: text, fontWeight: 500 },
  quesOptionDesc: { color: textMut, fontSize: "11px" },
  quesActions: { display: "flex", gap: "8px", marginTop: "8px" },
  quesSubmitBtn: {
    padding: "6px 16px",
    border: "none",
    borderRadius: "6px",
    background: accent,
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  quesCancelBtn: {
    padding: "6px 16px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    background: surface,
    color: textSec,
    fontSize: "12px",
    cursor: "pointer",
  },
  quesCustomInput: {
    padding: "6px 8px",
    border: `1px solid ${borderStrong}`,
    borderRadius: "6px",
    background: "#fff",
    color: text,
    fontSize: "12px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  archPanel: { padding: "16px", borderTop: `1px solid ${border}` },
  archTitle: {
    fontSize: "11px",
    color: textMut,
    marginBottom: "8px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  archLayer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "4px 0",
    fontSize: "12px",
    color: textSec,
  },
  archLayerDot: (layer: string): CSSProperties => ({
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: layerColors[layer] || "#9aa2b1",
  }),
  mainArea: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },

  // --- model switcher bar ---
  modelBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    borderBottom: `1px solid ${border}`,
    background: surface,
    flexWrap: "wrap",
  },
  modelLabel: { fontSize: "12px", color: textSec },
  select: {
    background: surface,
    color: text,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "6px 8px",
    fontSize: "12px",
    outline: "none",
    maxWidth: "230px",
  },
  baseUrlTag: {
    fontSize: "11px",
    color: textMut,
    fontFamily: "monospace",
    padding: "3px 6px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
  },
  reloadBtn: {
    marginLeft: "auto",
    padding: "6px 10px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: surface,
    color: textSec,
    fontSize: "12px",
    cursor: "pointer",
  },

  errorBanner: {
    padding: "12px 20px",
    background: "#fef2f2",
    borderBottom: "1px solid #fecaca",
    color: "#b91c1c",
    fontSize: "13px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  // P1-4: amber warning banner shown while the SSE stream is down (distinct
  // from the red errorBanner — this is recoverable and auto-retries).
  sseDownBanner: {
    padding: "10px 20px",
    background: "#fffbeb",
    borderBottom: "1px solid #fde68a",
    color: "#b45309",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
  },
  errorClose: {
    background: "none",
    border: "none",
    color: "#b91c1c",
    cursor: "pointer",
    fontSize: "18px",
  },
  welcome: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px",
    overflowY: "auto",
  },
  welcomeIcon: { fontSize: "64px", marginBottom: "16px" },
  welcomeTitle: { fontSize: "28px", fontWeight: 600, color: text, marginBottom: "8px" },
  welcomeText: { fontSize: "15px", color: textSec, marginBottom: "32px" },
  welcomeFeatures: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    maxWidth: "620px",
    marginBottom: "32px",
  },
  welcomeFeature: {
    display: "flex",
    gap: "12px",
    padding: "16px",
    background: surface,
    borderRadius: "12px",
    border: `1px solid ${border}`,
  },
  welcomeFeatureIcon: { fontSize: "24px" },
  welcomeFeatureTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: text,
    marginBottom: "4px",
  },
  welcomeFeatureDesc: { fontSize: "12px", color: textSec },
  welcomeBtn: {
    padding: "12px 32px",
    border: "none",
    borderRadius: "10px",
    background: accent,
    color: "#fff",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
  },
  welcomeStarting: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 32px",
    borderRadius: "10px",
    background: accentSoft,
    border: `1px solid ${border}`,
    color: accent,
    fontSize: "15px",
    fontWeight: 500,
  },
  welcomeSpinner: { fontSize: "18px" },
  // P1-4: de-emphasized "stage N/3 · waited Ns" hint inside the starting pill.
  welcomeProgress: {
    fontSize: "13px",
    fontWeight: 400,
    color: textSec,
  },
  noSession: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  noSessionIcon: { fontSize: "48px", marginBottom: "16px" },
  noSessionText: { fontSize: "14px", color: textSec, marginBottom: "16px" },
  newSessionLargeBtn: {
    padding: "10px 24px",
    border: "none",
    borderRadius: "10px",
    background: accent,
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  messagesArea: { flex: 1, overflowY: "auto", padding: "20px" },
  msgUser: { display: "flex", gap: "12px", marginBottom: "16px", justifyContent: "flex-end" },
  msgAssistant: { display: "flex", gap: "12px", marginBottom: "16px" },
  msgSystem: { display: "flex", justifyContent: "center", marginBottom: "12px" },
  systemNote: {
    fontSize: "11px",
    color: textSec,
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "999px",
    padding: "4px 12px",
  },
  msgAvatarUser: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: accent,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: 600,
    color: "#fff",
    order: 1,
    flexShrink: 0,
  },
  msgAvatarAssistant: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: surface,
    border: `1px solid ${border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    flexShrink: 0,
  },
  msgContent: { maxWidth: "76%", minWidth: 0 },
  msgRole: {
    fontSize: "11px",
    color: textMut,
    marginBottom: "4px",
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  modelTag: { color: accent, fontFamily: "monospace" },
  msgText: {
    fontSize: "14px",
    color: text,
    lineHeight: 1.6,
    background: surface,
    border: `1px solid ${border}`,
    padding: "12px 16px",
    borderRadius: "12px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  reasoningBox: {
    fontSize: "12px",
    color: textSec,
    lineHeight: 1.6,
    background: subtle,
    border: `1px dashed ${borderStrong}`,
    padding: "8px 12px",
    borderRadius: "10px",
    whiteSpace: "pre-wrap",
    marginBottom: "6px",
  },
  toolBox: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "6px",
    overflow: "hidden",
  },
  toolHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    fontSize: "12px",
    color: textSec,
    cursor: "pointer",
  },
  toolDot: (status: string): CSSProperties => ({
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    background: toolColors[status] || "#9aa2b1",
    flexShrink: 0,
  }),
  toolName: { fontFamily: "monospace", color: text },
  toolStatus: { marginLeft: "auto", fontSize: "11px", color: textMut },
  toolBody: {
    padding: "8px 12px",
    borderTop: `1px solid ${border}`,
    fontSize: "11px",
    fontFamily: "monospace",
    color: textSec,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: "260px",
    overflowY: "auto",
    margin: 0,
    background: subtle,
  },
  turnError: {
    fontSize: "12px",
    color: "#b91c1c",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    padding: "8px 12px",
    borderRadius: "10px",
    marginTop: "6px",
    whiteSpace: "pre-wrap",
  },

  // --- patch part (live, on assistant turns) + turn diff review card -----
  patchBox: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: textSec,
    maxWidth: "100%",
  },
  patchFiles: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    color: text,
  },
  patchHash: {
    fontSize: "10px",
    color: textMut,
    fontFamily: "ui-monospace, monospace",
    flexShrink: 0,
  },
  diffCard: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginTop: "6px",
    overflow: "hidden",
    textAlign: "left" as const,
  },
  diffCardTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    padding: "8px 12px",
    fontSize: "12px",
    fontWeight: 600,
    color: text,
    background: subtle,
    borderBottom: `1px solid ${border}`,
  },
  diffStatAdd: { color: "#16a34a", fontFamily: "ui-monospace, monospace" },
  diffStatDel: { color: "#dc2626", fontFamily: "ui-monospace, monospace" },
  diffFileRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 12px",
    fontSize: "12px",
    cursor: "pointer",
    color: textSec,
  },
  diffFileStatus: (status: string): CSSProperties => {
    const map: Record<string, { background: string; color: string }> = {
      added: { background: "rgba(22,163,74,0.12)", color: "#15803d" },
      modified: { background: "rgba(37,99,235,0.10)", color: "#1d4ed8" },
      deleted: { background: "rgba(220,38,38,0.10)", color: "#b91c1c" },
      renamed: { background: "rgba(139,92,246,0.12)", color: "#6d28d9" },
    };
    const s = map[status] || { background: subtle, color: textSec };
    return {
      fontSize: "10px",
      padding: "1px 6px",
      borderRadius: "6px",
      border: `1px solid ${border}`,
      flexShrink: 0,
      ...s,
    };
  },
  diffFileName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    color: text,
  },
  diffChevron: { fontSize: "10px", color: textMut, flexShrink: 0 },
  diffPatchBody: {
    margin: 0,
    padding: "6px 0",
    background: "#fbfcfd",
    borderTop: `1px solid ${border}`,
    borderBottom: `1px solid ${border}`,
    fontFamily: "ui-monospace, monospace",
    fontSize: "11px",
    lineHeight: 1.6,
    maxHeight: "280px",
    overflowY: "auto",
  },
  diffLine: { padding: "0 12px", whiteSpace: "pre-wrap", wordBreak: "break-all" },
  diffLineAdd: { color: "#067d47", background: "rgba(22,163,74,0.08)" },
  diffLineDel: { color: "#b91c1c", background: "rgba(220,38,38,0.08)" },
  diffLineHunk: { color: accent, background: accentSoft },
  diffLineMeta: { color: textMut },
  diffActions: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "8px 12px",
    background: subtle,
  },
  revertBtn: {
    padding: "5px 12px",
    border: `1px solid #dc2626`,
    borderRadius: "6px",
    background: "transparent",
    color: "#dc2626",
    fontSize: "12px",
    cursor: "pointer",
  },
  unrevertBtn: {
    padding: "5px 12px",
    border: `1px solid ${accent}`,
    borderRadius: "6px",
    background: "transparent",
    color: accent,
    fontSize: "12px",
    cursor: "pointer",
  },
  revertedNote: { fontSize: "12px", color: "#15803d" },

  // --- P1-2: protocol capability rendering --------------------------------
  // Session-level todo card (SSE `todo.updated`, not a message part).
  todoCard: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "10px",
    overflow: "hidden",
  },
  todoTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    fontSize: "12px",
    fontWeight: 600,
    color: text,
    background: subtle,
    borderBottom: `1px solid ${border}`,
  },
  todoItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "5px 12px",
    fontSize: "12px",
    color: textSec,
  },
  todoStatus: (status: string): CSSProperties => {
    const map: Record<string, { background: string; color: string }> = {
      pending: { background: subtle, color: textSec },
      in_progress: { background: accentSoft, color: accent },
      completed: { background: "rgba(22,163,74,0.12)", color: "#15803d" },
      cancelled: { background: "rgba(107,114,128,0.12)", color: textMut },
    };
    const s = map[status] || map.pending;
    return {
      fontSize: "10px",
      padding: "1px 7px",
      borderRadius: "6px",
      border: `1px solid ${border}`,
      flexShrink: 0,
      minWidth: "52px",
      textAlign: "center" as const,
      ...s,
    };
  },
  todoContent: { flex: 1, minWidth: 0, lineHeight: 1.5 },
  todoDone: { textDecoration: "line-through", color: textMut },
  // Context-compaction marker part.
  compactionBox: {
    background: "rgba(139,92,246,0.07)",
    border: `1px solid rgba(139,92,246,0.25)`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    color: "#6d28d9",
  },
  // Subagent delegation part.
  subtaskBox: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    color: textSec,
  },
  subtaskAgent: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "6px",
    border: `1px solid ${border}`,
    background: accentSoft,
    color: accent,
    flexShrink: 0,
  },
  // Failed-and-retried attempt part.
  retryBox: {
    background: "rgba(245,158,11,0.08)",
    border: `1px solid rgba(245,158,11,0.3)`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    color: "#b45309",
  },
  // File attachment part chip.
  fileChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "3px 10px",
    fontSize: "12px",
    color: textSec,
    marginBottom: "6px",
    maxWidth: "100%",
  },
  // Agent attribution marker chip.
  agentTagChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "11px",
    color: accent,
    background: accentSoft,
    borderRadius: "6px",
    padding: "1px 8px",
    marginBottom: "6px",
  },
  // Fork button on a user turn's role row.
  forkBtn: {
    marginLeft: "auto",
    border: "none",
    background: "transparent",
    color: textMut,
    cursor: "pointer",
    fontSize: "11px",
    padding: "1px 6px",
    borderRadius: "6px",
    flexShrink: 0,
  },
  // Regenerate button on the last assistant turn's role row.
  regenBtn: {
    marginLeft: "auto",
    border: "none",
    background: "transparent",
    color: textMut,
    cursor: "pointer",
    fontSize: "11px",
    padding: "1px 6px",
    borderRadius: "6px",
    flexShrink: 0,
  },
  turnMeta: { fontSize: "10px", color: textMut, marginTop: "4px" },
  streaming: { color: accent, fontSize: "11px" },
  cursor: { color: accent },
  inputArea: { display: "flex", flexDirection: "column", gap: "8px", padding: "16px", borderTop: `1px solid ${border}`, background: surface },
  inputRow: { display: "flex", gap: "8px", alignItems: "flex-end" },
  attachBar: { display: "flex", flexWrap: "wrap", gap: "6px" },
  skillChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "12px",
    background: accentSoft,
    border: `1px solid ${accent}`,
    color: accent,
    fontSize: "12px",
  },
  attachChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "12px",
    background: "rgba(16,185,129,0.10)",
    border: "1px solid #34d399",
    color: "#047857",
    fontSize: "12px",
    maxWidth: "260px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  agentChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "12px",
    background: "rgba(139,92,246,0.10)",
    border: "1px solid #a78bfa",
    color: "#6d28d9",
    fontSize: "12px",
  },
  chipRemove: {
    border: "none",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    padding: "0 2px",
    fontSize: "13px",
    lineHeight: 1,
  },
  skillPickerWrap: { position: "relative" },
  skillBtn: {
    padding: "10px 12px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: surface,
    color: textSec,
    fontSize: "13px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  skillBackdrop: { position: "fixed", inset: 0, zIndex: 40 },
  skillMenu: {
    position: "absolute",
    bottom: "48px",
    left: 0,
    width: "320px",
    maxHeight: "280px",
    overflowY: "auto",
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "12px",
    padding: "8px",
    zIndex: 50,
    boxShadow: "0 8px 24px rgba(15,23,42,0.12)",
  },
  skillMenuHeader: { fontSize: "12px", color: textSec, padding: "4px 6px 8px" },
  skillEmpty: { fontSize: "12px", color: textMut, padding: "8px 6px" },
  skillItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: text,
  },
  skillItemName: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  scopeProject: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(56,189,248,0.15)",
    color: "#0284c7",
    border: "1px solid rgba(56,189,248,0.4)",
  },
  scopeGlobal: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(250,204,21,0.18)",
    color: "#b45309",
    border: "1px solid rgba(250,204,21,0.5)",
  },
  scopeBuiltin: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(167,139,250,0.15)",
    color: "#7c3aed",
    border: "1px solid rgba(167,139,250,0.4)",
  },
  skillMenuClose: {
    width: "100%",
    marginTop: "8px",
    padding: "6px",
    border: "none",
    borderRadius: "6px",
    background: accent,
    color: "#fff",
    fontSize: "12px",
    cursor: "pointer",
  },

  chatBody: { flex: 1, display: "flex", overflow: "hidden", minHeight: 0 },
  chatColumn: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", minWidth: 0 },

  // --- @-mention autocomplete (files + agents) ---------------------------
  atMenuWrap: { position: "relative", flex: 1, display: "flex" },
  atMenu: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    marginBottom: "6px",
    width: "min(480px, 60vw)",
    maxHeight: "260px",
    overflowY: "auto",
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "12px",
    padding: "6px",
    zIndex: 60,
    boxShadow: "0 8px 24px rgba(15,23,42,0.12)",
  },
  atMenuHeader: { fontSize: "11px", color: textSec, padding: "4px 8px" },
  atItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: text,
  },
  atItemActive: {
    background: accentSoft,
  },
  atItemIcon: { flexShrink: 0 },
  atItemPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
  },
  atItemAgentName: {
    flexShrink: 0,
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: "#6d28d9",
    fontWeight: 600,
    minWidth: "80px",
  },
  atItemAgentDesc: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    color: textSec,
  },

  // --- Slash command menu (shares atMenu/atItem with @-mention) ----------
  cmdName: {
    flexShrink: 0,
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: text,
    minWidth: "80px",
  },
  cmdDesc: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    color: textSec,
  },
  cmdSource: {
    flexShrink: 0,
    fontSize: "10px",
    color: textSec,
    border: `1px solid ${border}`,
    borderRadius: "4px",
    padding: "1px 5px",
  },

  // --- Workspace file browser panel ---------------------------------------
  filesPanel: {
    width: "320px",
    flexShrink: 0,
    borderLeft: `1px solid ${border}`,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: surface,
  },
  filesPanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 12px",
    borderBottom: `1px solid ${border}`,
    fontSize: "13px",
    color: text,
    gap: "8px",
  },
  filesPanelBody: { flex: 1, overflowY: "auto", padding: "6px 4px" },
  wsUploadBtn: {
    border: `1px solid ${border}`,
    background: surface,
    color: text,
    cursor: "pointer",
    fontSize: "12px",
    borderRadius: "6px",
    padding: "3px 8px",
    flexShrink: 0,
  },
  wsNotice: {
    padding: "6px 12px",
    fontSize: "12px",
    color: "#047857",
    background: "rgba(16,185,129,0.08)",
    borderBottom: `1px solid ${border}`,
  },
  treeRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: textSec,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  treeRowHover: { color: text },
  treeFileSize: { marginLeft: "auto", fontSize: "11px", color: textMut, flexShrink: 0 },
  previewBack: {
    border: "none",
    background: "transparent",
    color: textSec,
    cursor: "pointer",
    fontSize: "12px",
    padding: "2px 4px",
  },
  previewBody: {
    flex: 1,
    overflowY: "auto",
    padding: "12px",
    fontSize: "13px",
    color: text,
    lineHeight: 1.6,
  },
  previewFrame: {
    width: "100%",
    height: "100%",
    border: "none",
    borderRadius: "8px",
    background: "#fff",
  },
  previewPre: {
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: text,
    background: subtle,
    padding: "10px",
    borderRadius: "8px",
  },
  previewImg: { maxWidth: "100%", borderRadius: "8px", display: "block", margin: "0 auto" },
  previewBinary: { color: textMut, padding: "24px 0", textAlign: "center" as const },
  mdTitle: { fontSize: "16px", fontWeight: 700, color: text, margin: "12px 0 6px" },
  mdH2: { fontSize: "14px", fontWeight: 700, color: text, margin: "10px 0 4px" },
  mdP: { margin: "6px 0" },
  mdLi: { margin: "2px 0", paddingLeft: "8px", listStyle: "disc inside" as const },
  mdCode: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    background: subtle,
    padding: "1px 5px",
    borderRadius: "4px",
    color: "#1d4ed8",
  },
  mdCodeBlock: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    background: subtle,
    padding: "10px",
    borderRadius: "8px",
    overflowX: "auto",
    whiteSpace: "pre",
    margin: "8px 0",
    color: text,
  },
  mdStrong: { color: text, fontWeight: 700 },
  textInput: {
    flex: 1,
    padding: "12px 16px",
    border: `1px solid ${border}`,
    borderRadius: "10px",
    background: page,
    color: text,
    fontSize: "14px",
    outline: "none",
    resize: "none",
    fontFamily: "inherit",
    maxHeight: "160px",
  },
  sendBtn: {
    padding: "12px 24px",
    border: "none",
    borderRadius: "10px",
    background: accent,
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  abortBtn: {
    padding: "12px 24px",
    border: "none",
    borderRadius: "10px",
    background: "#dc2626",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: surface,
    borderRadius: "12px",
    width: "760px",
    maxWidth: "92vw",
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column",
    border: `1px solid ${border}`,
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    borderBottom: `1px solid ${border}`,
    fontSize: "15px",
    fontWeight: 600,
    color: text,
  },
  modalClose: {
    background: "none",
    border: "none",
    color: textSec,
    cursor: "pointer",
    fontSize: "20px",
  },
  modalBody: {
    padding: "16px",
    overflow: "auto",
    fontSize: "12px",
    fontFamily: "monospace",
    color: textSec,
    whiteSpace: "pre-wrap",
    margin: 0,
  },

  // --- fastk chunk 引用徽章 + 内容查看器 ---------------------------------
  // 徽章：行内可点击，展示知识库来源；中文文案，悬停有提示。
  chunkBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    padding: "0 8px",
    margin: "0 2px",
    height: "20px",
    borderRadius: "10px",
    background: accentSoft,
    border: "1px solid rgba(37,99,235,0.25)",
    color: accent,
    fontSize: "12px",
    lineHeight: "18px",
    cursor: "pointer",
    verticalAlign: "baseline",
    whiteSpace: "nowrap",
    userSelect: "none",
  },
  chunkViewerBody: {
    padding: "16px",
    overflow: "auto",
    fontSize: "14px",
    color: text,
    lineHeight: 1.75,
    margin: 0,
    // 中文正文排版：中文优先字体栈；strict 禁则避免标点悬挂行首；
    // anywhere 兜底长 URL/英文词的断行。
    fontFamily:
      '-apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    lineBreak: "strict",
    overflowWrap: "anywhere",
  },
  chunkMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    padding: "10px 12px",
    marginBottom: "12px",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    fontSize: "12px",
    color: textSec,
  },
  chunkMetaRow: { display: "flex", gap: "6px", alignItems: "baseline" },
  chunkMetaLabel: {
    flexShrink: 0,
    color: textMut,
    // 中文标签与西文路径混排时保持 12px 可读性
    fontSize: "12px",
  },
  chunkMetaValue: { color: text, fontFamily: "ui-monospace, monospace", wordBreak: "break-all" },
  chunkText: {
    whiteSpace: "pre-wrap",
    textAlign: "justify", // 中文两端对齐，避免右侧参差
  },
  chunkImage: {
    display: "block",
    maxWidth: "100%",
    marginTop: "12px",
    borderRadius: "8px",
    border: `1px solid ${border}`,
  },
  chunkImagePlaceholder: {
    display: "block",
    marginTop: "12px",
    padding: "28px 0",
    textAlign: "center",
    color: textMut,
    fontSize: "13px",
    border: `1px dashed ${border}`,
    borderRadius: "8px",
  },
  chunkImageError: {
    display: "block",
    marginTop: "12px",
    padding: "28px 0",
    textAlign: "center",
    color: "#b91c1c",
    fontSize: "13px",
    border: "1px dashed #fecaca",
    borderRadius: "8px",
    background: "#fefafa",
  },
  chunkLoading: {
    padding: "24px 0",
    textAlign: "center",
    color: textMut,
    fontSize: "13px",
  },
  chunkError: {
    padding: "16px",
    textAlign: "center",
    color: "#b91c1c",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "8px",
    fontSize: "13px",
  },
};
