import type { CSSProperties } from "react";

export const layerColors: Record<string, string> = {
  browser: "#3b82f6",
  platform: "#8b5cf6",
  container: "#06b6d4",
  shared: "#10b981",
};

const toolColors: Record<string, string> = {
  pending: "#52525b",
  running: "#f59e0b",
  completed: "#22c55e",
  error: "#ef4444",
};

/** `any` because a few entries are style factories, not plain CSSProperties. */
export const styles: Record<string, any> = {
  container: { display: "flex", height: "100vh", background: "#0f1117" },
  sidebar: {
    width: "300px",
    borderRight: "1px solid #2a2d3a",
    display: "flex",
    flexDirection: "column",
    background: "#13141c",
  },
  sidebarHeader: { padding: "16px", borderBottom: "1px solid #2a2d3a" },
  brand: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "12px" },
  brandIcon: { fontSize: "20px" },
  brandText: { fontSize: "16px", fontWeight: 600, color: "#e4e4e7" },
  userInfo: { display: "flex", alignItems: "center", gap: "8px" },
  userAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    background: "#6366f1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: 600,
    color: "#fff",
  },
  userName: { flex: 1, fontSize: "13px", color: "#a1a1aa" },
  logoutBtn: {
    background: "none",
    border: "1px solid #2a2d3a",
    color: "#71717a",
    padding: "4px 8px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
  },
  statusPanel: { padding: "16px", borderBottom: "1px solid #2a2d3a" },
  statusRow: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" },
  statusDot: { width: "8px", height: "8px", borderRadius: "50%" },
  statusText: { fontSize: "14px", fontWeight: 500, color: "#e4e4e7" },
  containerName: {
    fontSize: "12px",
    color: "#71717a",
    marginBottom: "4px",
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusDetail: { fontSize: "11px", color: "#52525b", marginBottom: "10px" },
  runtimeBox: {
    fontSize: "11px",
    color: "#52525b",
    background: "#101119",
    border: "1px solid #22242f",
    borderRadius: "6px",
    padding: "8px",
    marginBottom: "10px",
    lineHeight: 1.6,
  },
  runtimeKey: { color: "#71717a" },
  runtimeVal: { color: "#a1a1aa", fontFamily: "monospace" },
  statusButtons: { display: "flex", gap: "8px" },
  startBtn: {
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "6px",
    background: "#22c55e",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  stopBtn: {
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "6px",
    background: "#ef4444",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  logBtn: {
    padding: "8px 12px",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    background: "transparent",
    color: "#a1a1aa",
    fontSize: "13px",
    cursor: "pointer",
  },
  sessionsSection: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  sessionsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    fontSize: "13px",
    color: "#71717a",
    fontWeight: 500,
  },
  newSessionBtn: {
    width: "24px",
    height: "24px",
    border: "1px solid #2a2d3a",
    borderRadius: "4px",
    background: "transparent",
    color: "#a1a1aa",
    fontSize: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sessionsList: { flex: 1, overflowY: "auto", padding: "0 8px" },
  emptySessions: { padding: "16px", fontSize: "12px", color: "#52525b", textAlign: "center" },
  sessionItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: "#a1a1aa",
  },
  sessionItemActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: "#e4e4e7",
    background: "#2a2d3a",
  },
  sessionIcon: { fontSize: "14px" },
  sessionTitle: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionItemActiveTitle: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionActions: { display: "flex", gap: "4px", marginLeft: "auto", flexShrink: 0 },
  sessionActionBtn: {
    width: "20px",
    height: "20px",
    border: "none",
    borderRadius: "4px",
    background: "transparent",
    color: "#52525b",
    fontSize: "11px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },

  // --- permission / question approval cards ---
  permCard: {
    background: "#1f1a10",
    border: "1px solid #a16207",
    borderRadius: "8px",
    padding: "12px 16px",
    marginBottom: "12px",
  },
  permTitle: { fontSize: "13px", fontWeight: 600, color: "#fbbf24", marginBottom: "6px" },
  permRes: {
    fontSize: "12px",
    color: "#a1a1aa",
    fontFamily: "monospace",
    background: "#15161f",
    borderRadius: "4px",
    padding: "4px 8px",
    marginBottom: "4px",
    wordBreak: "break-all",
  },
  permActions: { display: "flex", gap: "8px", marginTop: "10px" },
  permAllowBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    background: "#22c55e",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  permAlwaysBtn: {
    padding: "6px 12px",
    border: "1px solid #22c55e",
    borderRadius: "6px",
    background: "transparent",
    color: "#22c55e",
    fontSize: "12px",
    cursor: "pointer",
  },
  permRejectBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    background: "#ef4444",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  quesCard: {
    background: "#12142a",
    border: "1px solid #4f46e5",
    borderRadius: "8px",
    padding: "12px 16px",
    marginBottom: "12px",
  },
  quesTitle: { fontSize: "13px", fontWeight: 600, color: "#a5b4fc", marginBottom: "8px" },
  quesQuestion: { fontSize: "13px", color: "#e4e4e7", marginBottom: "4px" },
  quesOptions: { display: "flex", flexDirection: "column", gap: "4px", marginBottom: "8px" },
  quesOption: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    fontSize: "12px",
    color: "#a1a1aa",
    cursor: "pointer",
  },
  quesOptionLabel: { color: "#e4e4e7", fontWeight: 500 },
  quesOptionDesc: { color: "#71717a", fontSize: "11px" },
  quesActions: { display: "flex", gap: "8px", marginTop: "8px" },
  quesSubmitBtn: {
    padding: "6px 16px",
    border: "none",
    borderRadius: "6px",
    background: "#6366f1",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  quesCancelBtn: {
    padding: "6px 16px",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    background: "transparent",
    color: "#71717a",
    fontSize: "12px",
    cursor: "pointer",
  },
  quesCustomInput: {
    padding: "6px 8px",
    border: "1px solid #3f3f46",
    borderRadius: "6px",
    background: "#15161f",
    color: "#e4e4e7",
    fontSize: "12px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  archPanel: { padding: "16px", borderTop: "1px solid #2a2d3a" },
  archTitle: {
    fontSize: "11px",
    color: "#52525b",
    marginBottom: "8px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  archLayer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "4px 0",
    fontSize: "12px",
    color: "#71717a",
  },
  archLayerDot: (layer: string): CSSProperties => ({
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: layerColors[layer] || "#52525b",
  }),
  mainArea: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },

  // --- model switcher bar ---
  modelBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    borderBottom: "1px solid #2a2d3a",
    background: "#13141c",
    flexWrap: "wrap",
  },
  modelLabel: { fontSize: "12px", color: "#71717a" },
  select: {
    background: "#1a1b26",
    color: "#e4e4e7",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    padding: "6px 8px",
    fontSize: "12px",
    outline: "none",
    maxWidth: "230px",
  },
  baseUrlTag: {
    fontSize: "11px",
    color: "#52525b",
    fontFamily: "monospace",
    padding: "3px 6px",
    border: "1px solid #22242f",
    borderRadius: "4px",
  },
  reloadBtn: {
    marginLeft: "auto",
    padding: "6px 10px",
    border: "1px solid #2a2d3a",
    borderRadius: "6px",
    background: "transparent",
    color: "#a1a1aa",
    fontSize: "12px",
    cursor: "pointer",
  },

  errorBanner: {
    padding: "12px 20px",
    background: "#7f1d1d",
    color: "#fca5a5",
    fontSize: "13px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  errorClose: {
    background: "none",
    border: "none",
    color: "#fca5a5",
    cursor: "pointer",
    fontSize: "18px",
  },
  welcome: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px",
    overflowY: "auto",
  },
  welcomeIcon: { fontSize: "64px", marginBottom: "16px" },
  welcomeTitle: { fontSize: "28px", fontWeight: 600, color: "#e4e4e7", marginBottom: "8px" },
  welcomeText: { fontSize: "15px", color: "#71717a", marginBottom: "32px" },
  welcomeFeatures: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    maxWidth: "620px",
    marginBottom: "32px",
  },
  welcomeFeature: {
    display: "flex",
    gap: "12px",
    padding: "16px",
    background: "#1a1b26",
    borderRadius: "8px",
    border: "1px solid #2a2d3a",
  },
  welcomeFeatureIcon: { fontSize: "24px" },
  welcomeFeatureTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#e4e4e7",
    marginBottom: "4px",
  },
  welcomeFeatureDesc: { fontSize: "12px", color: "#71717a" },
  welcomeBtn: {
    padding: "12px 32px",
    border: "none",
    borderRadius: "8px",
    background: "#6366f1",
    color: "#fff",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
  },
  // Startup-in-progress strip shown in place of the welcome button while a
  // background container start is in flight (creating / starting / warming).
  welcomeStarting: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 32px",
    borderRadius: "8px",
    background: "#1f2030",
    border: "1px solid #2a2d3a",
    color: "#a5b4fc",
    fontSize: "15px",
    fontWeight: 500,
  },
  welcomeSpinner: { fontSize: "18px" },
  noSession: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  noSessionIcon: { fontSize: "48px", marginBottom: "16px" },
  noSessionText: { fontSize: "14px", color: "#71717a", marginBottom: "16px" },
  newSessionLargeBtn: {
    padding: "10px 24px",
    border: "none",
    borderRadius: "8px",
    background: "#6366f1",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  messagesArea: { flex: 1, overflowY: "auto", padding: "20px" },
  msgUser: { display: "flex", gap: "12px", marginBottom: "16px", justifyContent: "flex-end" },
  msgAssistant: { display: "flex", gap: "12px", marginBottom: "16px" },
  msgSystem: { display: "flex", justifyContent: "center", marginBottom: "12px" },
  systemNote: {
    fontSize: "11px",
    color: "#71717a",
    background: "#16171f",
    border: "1px solid #22242f",
    borderRadius: "999px",
    padding: "4px 12px",
  },
  msgAvatarUser: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: "#6366f1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: 600,
    color: "#fff",
    order: 1,
    flexShrink: 0,
  },
  msgAvatarAssistant: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: "#1a1b26",
    border: "1px solid #2a2d3a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    flexShrink: 0,
  },
  msgContent: { maxWidth: "76%", minWidth: 0 },
  msgRole: {
    fontSize: "11px",
    color: "#52525b",
    marginBottom: "4px",
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  modelTag: { color: "#6366f1", fontFamily: "monospace" },
  msgText: {
    fontSize: "14px",
    color: "#e4e4e7",
    lineHeight: 1.6,
    background: "#1a1b26",
    padding: "12px 16px",
    borderRadius: "8px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  reasoningBox: {
    fontSize: "12px",
    color: "#8b8b96",
    lineHeight: 1.6,
    background: "#15161f",
    border: "1px dashed #2a2d3a",
    padding: "8px 12px",
    borderRadius: "8px",
    whiteSpace: "pre-wrap",
    marginBottom: "6px",
  },
  toolBox: {
    background: "#15161f",
    border: "1px solid #22242f",
    borderRadius: "8px",
    marginBottom: "6px",
    overflow: "hidden",
  },
  toolHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    fontSize: "12px",
    color: "#a1a1aa",
    cursor: "pointer",
  },
  toolDot: (status: string): CSSProperties => ({
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    background: toolColors[status] || "#52525b",
    flexShrink: 0,
  }),
  toolName: { fontFamily: "monospace", color: "#e4e4e7" },
  toolStatus: { marginLeft: "auto", fontSize: "11px", color: "#52525b" },
  toolBody: {
    padding: "8px 12px",
    borderTop: "1px solid #22242f",
    fontSize: "11px",
    fontFamily: "monospace",
    color: "#8b8b96",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: "260px",
    overflowY: "auto",
    margin: 0,
  },
  turnError: {
    fontSize: "12px",
    color: "#fca5a5",
    background: "#2a1416",
    border: "1px solid #7f1d1d",
    padding: "8px 12px",
    borderRadius: "8px",
    marginTop: "6px",
    whiteSpace: "pre-wrap",
  },
  turnMeta: { fontSize: "10px", color: "#3f3f46", marginTop: "4px" },
  streaming: { color: "#6366f1", fontSize: "11px" },
  cursor: { color: "#6366f1" },
  inputArea: { display: "flex", flexDirection: "column", gap: "8px", padding: "16px", borderTop: "1px solid #2a2d3a" },
  inputRow: { display: "flex", gap: "8px", alignItems: "flex-end" },
  attachBar: { display: "flex", flexWrap: "wrap", gap: "6px" },
  skillChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "12px",
    background: "rgba(99,102,241,0.15)",
    border: "1px solid #6366f1",
    color: "#a5b4fc",
    fontSize: "12px",
  },
  attachChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "12px",
    background: "rgba(52,211,153,0.12)",
    border: "1px solid #34d399",
    color: "#6ee7b7",
    fontSize: "12px",
    maxWidth: "260px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chipRemove: {
    border: "none",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    padding: "0 2px",
    fontSize: "13px",
    lineHeight: 1,
  },
  skillPickerWrap: { position: "relative" },
  skillBtn: {
    padding: "10px 12px",
    border: "1px solid #2a2d3a",
    borderRadius: "8px",
    background: "#1a1b26",
    color: "#a1a1aa",
    fontSize: "13px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  skillBackdrop: { position: "fixed", inset: 0, zIndex: 40 },
  skillMenu: {
    position: "absolute",
    bottom: "48px",
    left: 0,
    width: "320px",
    maxHeight: "280px",
    overflowY: "auto",
    background: "#16171f",
    border: "1px solid #2a2d3a",
    borderRadius: "10px",
    padding: "8px",
    zIndex: 50,
    boxShadow: "0 8px 24px rgba(0,0,0,0.5)",
  },
  skillMenuHeader: { fontSize: "12px", color: "#a1a1aa", padding: "4px 6px 8px" },
  skillEmpty: { fontSize: "12px", color: "#52525b", padding: "8px 6px" },
  skillItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: "#d4d4d8",
  },
  skillItemName: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  scopeProject: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(56,189,248,0.15)",
    color: "#38bdf8",
    border: "1px solid rgba(56,189,248,0.4)",
  },
  scopeGlobal: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(250,204,21,0.12)",
    color: "#facc15",
    border: "1px solid rgba(250,204,21,0.4)",
  },
  skillMenuClose: {
    width: "100%",
    marginTop: "8px",
    padding: "6px",
    border: "none",
    borderRadius: "6px",
    background: "#6366f1",
    color: "#fff",
    fontSize: "12px",
    cursor: "pointer",
  },

  chatBody: { flex: 1, display: "flex", overflow: "hidden", minHeight: 0 },
  chatColumn: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", minWidth: 0 },

  // --- @-mention file autocomplete ---------------------------------------
  atMenuWrap: { position: "relative", flex: 1, display: "flex" },
  atMenu: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    marginBottom: "6px",
    width: "min(480px, 60vw)",
    maxHeight: "240px",
    overflowY: "auto",
    background: "#16171f",
    border: "1px solid #2a2d3a",
    borderRadius: "10px",
    padding: "6px",
    zIndex: 60,
    boxShadow: "0 8px 24px rgba(0,0,0,0.5)",
  },
  atMenuHeader: { fontSize: "11px", color: "#a1a1aa", padding: "4px 8px" },
  atItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: "#d4d4d8",
  },
  atItemActive: {
    background: "rgba(99,102,241,0.2)",
  },
  atItemIcon: { flexShrink: 0 },
  atItemPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
  },

  // --- Slash command menu (shares atMenu/atItem with @-mention) ----------
  cmdName: {
    flexShrink: 0,
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: "#e4e4e7",
    minWidth: "80px",
  },
  cmdDesc: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    color: "#a1a1aa",
  },
  cmdSource: {
    flexShrink: 0,
    fontSize: "10px",
    color: "#71717a",
    border: "1px solid #2a2d3a",
    borderRadius: "4px",
    padding: "1px 5px",
  },

  // --- Workspace file browser panel ---------------------------------------
  filesPanel: {
    width: "320px",
    flexShrink: 0,
    borderLeft: "1px solid #2a2d3a",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "#111218",
  },
  filesPanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 12px",
    borderBottom: "1px solid #2a2d3a",
    fontSize: "13px",
    color: "#d4d4d8",
    gap: "8px",
  },
  filesPanelBody: { flex: 1, overflowY: "auto", padding: "6px 4px" },
  treeRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  treeRowHover: { color: "#e4e4e7" },
  treeFileSize: { marginLeft: "auto", fontSize: "11px", color: "#52525b", flexShrink: 0 },
  previewBack: {
    border: "none",
    background: "transparent",
    color: "#a1a1aa",
    cursor: "pointer",
    fontSize: "12px",
    padding: "2px 4px",
  },
  previewBody: {
    flex: 1,
    overflowY: "auto",
    padding: "12px",
    fontSize: "13px",
    color: "#d4d4d8",
    lineHeight: 1.6,
  },
  previewFrame: {
    width: "100%",
    height: "100%",
    border: "none",
    borderRadius: "8px",
    background: "#fff",
  },
  previewPre: {
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: "#c9ccd6",
    background: "#16171f",
    padding: "10px",
    borderRadius: "8px",
  },
  previewImg: { maxWidth: "100%", borderRadius: "8px", display: "block", margin: "0 auto" },
  previewBinary: { color: "#52525b", padding: "24px 0", textAlign: "center" as const },
  mdTitle: { fontSize: "16px", fontWeight: 700, color: "#f4f4f5", margin: "12px 0 6px" },
  mdH2: { fontSize: "14px", fontWeight: 700, color: "#e4e4e7", margin: "10px 0 4px" },
  mdP: { margin: "6px 0" },
  mdLi: { margin: "2px 0", paddingLeft: "8px", listStyle: "disc inside" as const },
  mdCode: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    background: "#16171f",
    padding: "1px 5px",
    borderRadius: "4px",
    color: "#93c5fd",
  },
  mdCodeBlock: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    background: "#16171f",
    padding: "10px",
    borderRadius: "8px",
    overflowX: "auto",
    whiteSpace: "pre",
    margin: "8px 0",
    color: "#c9ccd6",
  },
  mdStrong: { color: "#f4f4f5", fontWeight: 700 },
  textInput: {
    flex: 1,
    padding: "12px 16px",
    border: "1px solid #2a2d3a",
    borderRadius: "8px",
    background: "#1a1b26",
    color: "#e4e4e7",
    fontSize: "14px",
    outline: "none",
    resize: "none",
    fontFamily: "inherit",
    maxHeight: "160px",
  },
  sendBtn: {
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    background: "#6366f1",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  abortBtn: {
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    background: "#ef4444",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: "#1a1b26",
    borderRadius: "8px",
    width: "760px",
    maxWidth: "92vw",
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column",
    border: "1px solid #2a2d3a",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    borderBottom: "1px solid #2a2d3a",
    fontSize: "15px",
    fontWeight: 600,
    color: "#e4e4e7",
  },
  modalClose: {
    background: "none",
    border: "none",
    color: "#71717a",
    cursor: "pointer",
    fontSize: "20px",
  },
  modalBody: {
    padding: "16px",
    overflow: "auto",
    fontSize: "12px",
    fontFamily: "monospace",
    color: "#a1a1aa",
    whiteSpace: "pre-wrap",
    margin: 0,
  },
};
