import type { CSSProperties } from "react";

/**
 * Agent Docker Platform chat styles, aligned with design/hifi-redesign.html.
 *
 * All colors resolve through CSS custom properties defined in src/theme.css
 * (dark by default, light via html[data-theme="light"]), so every style below
 * is automatically theme-aware.
 */

/** Architecture layer dots (constant across themes, matching the prototype). */
export const layerColors: Record<string, string> = {
  browser: "#38bdf8",
  platform: "#a78bfa",
  container: "#22d3ee",
  shared: "#f59e0b",
};

const toolColors: Record<string, string> = {
  pending: "var(--text-3)",
  running: "var(--amber)",
  completed: "var(--green)",
  error: "var(--red)",
};

// Shared tokens (theme-aware, resolved by theme.css) ------------------------
const border = "var(--border)";
const borderStrong = "var(--border-strong)";
const surface = "var(--surface)";
const subtle = "var(--surface-2)";
const page = "var(--bg)";
const text = "var(--text)";
const textSec = "var(--text-2)";
const textMut = "var(--text-3)";
const accent = "var(--primary)";
const accentSoft = "var(--primary-soft)";

/** `any` because a few entries are style factories, not plain CSSProperties. */
export const styles: Record<string, any> = {
  container: { display: "flex", height: "100vh", background: page, color: text },
  // 侧栏边缘拖拽调宽手柄（flex 行内 6px 竖条，hover/拖动高亮见 theme.css
  // 的 .panel-resizer）。宽度状态由 Chat 组件管理并持久化。
  panelDragHandle: {
    width: "6px",
    flexShrink: 0,
    cursor: "col-resize",
    background: "transparent",
    zIndex: 20,
  },
  sidebar: {
    width: "300px",
    flexShrink: 0,
    borderRight: `1px solid ${border}`,
    display: "flex",
    flexDirection: "column",
    background: surface,
  },
  sidebarHeader: { padding: "16px", borderBottom: `1px solid ${border}` },
  brand: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "12px" },
  brandIcon: { fontSize: "20px" },
  brandText: { fontSize: "16px", fontWeight: 600, color: text },
  userInfo: { display: "flex", alignItems: "center", gap: "8px" },
  userAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    background: accent,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: 600,
    color: "#fff",
  },
  userName: { flex: 1, fontSize: "13px", color: textSec },
  logoutBtn: {
    background: "none",
    border: `1px solid ${border}`,
    color: textSec,
    padding: "4px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "12px",
  },
  statusPanel: { padding: "16px", borderBottom: `1px solid ${border}` },
  statusRow: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" },
  statusDot: { width: "8px", height: "8px", borderRadius: "50%" },
  statusText: { fontSize: "14px", fontWeight: 500, color: text },
  containerName: {
    fontSize: "12px",
    color: textSec,
    marginBottom: "4px",
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusDetail: { fontSize: "11px", color: textMut, marginBottom: "10px" },
  runtimeBox: {
    fontSize: "11px",
    color: textMut,
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "8px",
    marginBottom: "10px",
    lineHeight: 1.6,
  },
  runtimeKey: { color: textSec },
  runtimeVal: { color: text, fontFamily: "monospace" },
  statusButtons: { display: "flex", gap: "8px" },
  startBtn: {
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "8px",
    background: "var(--green-fill)",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  stopBtn: {
    flex: 1,
    padding: "8px",
    border: "none",
    borderRadius: "8px",
    background: "var(--red-fill)",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  logBtn: {
    padding: "8px 12px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: surface,
    color: textSec,
    fontSize: "13px",
    cursor: "pointer",
  },
  // --- 知识库展示区（紧邻 statusPanel 的"工作区"信息下方） ---
  kbPanel: { padding: "12px 16px", borderBottom: `1px solid ${border}` },
  kbPanelHeader: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" },
  kbPanelTitle: { fontSize: "13px", fontWeight: 500, color: textSec },
  kbCount: {
    fontSize: "11px",
    color: textMut,
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    padding: "0 7px",
    lineHeight: "18px",
  },
  kbRefresh: {
    marginLeft: "auto",
    width: "22px",
    height: "22px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    background: surface,
    color: textSec,
    fontSize: "13px",
    lineHeight: 1,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  kbList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    maxHeight: "200px",
    overflowY: "auto",
  },
  kbItem: {
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "7px 9px",
  },
  kbName: { fontSize: "12px", fontWeight: 600, color: text, fontFamily: "monospace" },
  kbDesc: { fontSize: "11px", color: textMut, marginTop: "3px", lineHeight: 1.5 },
  kbEmpty: { fontSize: "11px", color: textMut, padding: "4px 0" },
  sessionsSection: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  sessionsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    fontSize: "13px",
    color: textSec,
    fontWeight: 500,
  },
  newSessionBtn: {
    width: "24px",
    height: "24px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    background: surface,
    color: textSec,
    fontSize: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sessionsList: { flex: 1, overflowY: "auto", padding: "0 8px" },
  emptySessions: { padding: "16px", fontSize: "12px", color: textMut, textAlign: "center" },
  sessionItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    color: textSec,
  },
  sessionItemActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    color: text,
    background: accentSoft,
  },
  sessionIcon: { fontSize: "14px" },
  sessionTitle: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionItemActiveTitle: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionActions: { display: "flex", gap: "4px", marginLeft: "auto", flexShrink: 0 },
  sessionActionBtn: {
    width: "20px",
    height: "20px",
    border: "none",
    borderRadius: "4px",
    background: "transparent",
    color: textMut,
    fontSize: "11px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },

  // --- 项目区：侧栏下半部分，项目行可展开/收起，会话按目录归入项目 ---
  projectsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 16px 6px",
    marginTop: "8px",
    borderTop: `1px solid ${border}`,
    fontSize: "13px",
    color: textSec,
    fontWeight: 500,
  },
  emptyProjects: { padding: "8px 16px", fontSize: "12px", color: textMut, textAlign: "center" },
  projectRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "7px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 500,
    color: text,
  },
  projectCaret: { width: "12px", flexShrink: 0, fontSize: "10px", color: textMut },
  projectName: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  projectCount: {
    fontSize: "11px",
    color: textMut,
    background: subtle,
    borderRadius: "8px",
    padding: "0 6px",
    lineHeight: "16px",
    flexShrink: 0,
  },
  nestedSessionItem: { marginLeft: "18px" },
  emptyProjectSessions: {
    marginLeft: "18px",
    padding: "4px 12px",
    fontSize: "12px",
    color: textMut,
  },

  // --- 新建项目弹窗 ---
  projModalContent: {
    background: surface,
    borderRadius: "12px",
    width: "440px",
    maxWidth: "92vw",
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column",
    border: `1px solid ${border}`,
  },
  projModalBody: { padding: "16px", overflow: "auto", display: "flex", flexDirection: "column" },
  projLabel: { fontSize: "12px", color: textSec, fontWeight: 600, margin: "8px 0 6px" },
  projInput: {
    padding: "8px 10px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: page,
    color: text,
    fontSize: "13px",
    outline: "none",
  },
  projRadioRow: { display: "flex", flexDirection: "column", gap: "6px" },
  projRadio: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "13px",
    color: textSec,
    cursor: "pointer",
  },
  projDirEmpty: { padding: "10px 0", fontSize: "12px", color: textMut },
  projDirList: {
    marginTop: "8px",
    maxHeight: "200px",
    overflowY: "auto",
    border: `1px solid ${border}`,
    borderRadius: "8px",
  },
  projDirItem: {
    padding: "7px 10px",
    fontSize: "13px",
    color: textSec,
    cursor: "pointer",
    borderBottom: `1px solid ${border}`,
  },
  projDirItemActive: {
    padding: "7px 10px",
    fontSize: "13px",
    color: text,
    cursor: "pointer",
    background: accentSoft,
    borderBottom: `1px solid ${border}`,
  },
  projHint: { marginTop: "10px", fontSize: "12px", color: textMut, lineHeight: 1.5 },
  projFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    padding: "12px 16px",
    borderTop: `1px solid ${border}`,
  },
  projCancelBtn: {
    padding: "7px 14px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: surface,
    color: textSec,
    fontSize: "13px",
    cursor: "pointer",
  },
  projSubmitBtn: {
    padding: "7px 14px",
    border: "none",
    borderRadius: "8px",
    background: accent,
    color: "#fff",
    fontSize: "13px",
    cursor: "pointer",
  },

  // --- permission / question approval cards ---
  permCard: {
    background: "var(--amber-soft)",
    border: "1px solid var(--amber-border)",
    borderRadius: "10px",
    padding: "12px 16px",
    marginBottom: "12px",
  },
  permTitle: { fontSize: "13px", fontWeight: 600, color: "var(--amber)", marginBottom: "6px" },
  permRes: {
    fontSize: "12px",
    color: textSec,
    fontFamily: "monospace",
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "6px",
    padding: "4px 8px",
    marginBottom: "4px",
    wordBreak: "break-all",
  },
  // P1-5: pretty-printed tool input arguments on the approval card.
  permMeta: {
    margin: "8px 0 0",
    padding: "8px 10px",
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "6px",
    fontSize: "11px",
    color: textSec,
    fontFamily: "monospace",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: "200px",
    overflowY: "auto",
  },
  permActions: { display: "flex", gap: "8px", marginTop: "10px" },
  permAllowBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    background: "var(--green-fill)",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  permAlwaysBtn: {
    padding: "6px 12px",
    border: "1px solid var(--green)",
    borderRadius: "6px",
    background: "transparent",
    color: "var(--green)",
    fontSize: "12px",
    cursor: "pointer",
  },
  permRejectBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    background: "var(--red-fill)",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  quesCard: {
    background: "var(--indigo-soft)",
    border: "1px solid var(--indigo-border)",
    borderRadius: "10px",
    padding: "12px 16px",
    marginBottom: "12px",
  },
  quesTitle: { fontSize: "13px", fontWeight: 600, color: "var(--indigo)", marginBottom: "8px" },
  quesQuestion: { fontSize: "13px", color: text, marginBottom: "4px" },
  quesOptions: { display: "flex", flexDirection: "column", gap: "4px", marginBottom: "8px" },
  quesOption: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    fontSize: "12px",
    color: textSec,
    cursor: "pointer",
  },
  quesOptionLabel: { color: text, fontWeight: 500 },
  quesOptionDesc: { color: textMut, fontSize: "11px" },
  quesActions: { display: "flex", gap: "8px", marginTop: "8px" },
  quesSubmitBtn: {
    padding: "6px 16px",
    border: "none",
    borderRadius: "6px",
    background: accent,
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  quesCancelBtn: {
    padding: "6px 16px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
    background: surface,
    color: textSec,
    fontSize: "12px",
    cursor: "pointer",
  },
  quesCustomInput: {
    padding: "6px 8px",
    border: `1px solid ${borderStrong}`,
    borderRadius: "6px",
    background: surface,
    color: text,
    fontSize: "12px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  archPanel: { padding: "16px", borderTop: `1px solid ${border}` },
  archTitle: {
    fontSize: "11px",
    color: textMut,
    marginBottom: "8px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  archLayer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "4px 0",
    fontSize: "12px",
    color: textSec,
  },
  archLayerDot: (layer: string): CSSProperties => ({
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: layerColors[layer] || textMut,
  }),
  mainArea: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },

  // --- model switcher bar（对齐原型 .modelbar：54px 高、左会话标题 + 右状态区） ---
  modelBar: {
    height: "54px",
    flex: "none",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "0 16px",
    borderBottom: `1px solid ${border}`,
    background: surface,
  },
  mbLeft: { flex: 1, minWidth: 0, display: "flex", alignItems: "center" },
  mbSess: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    fontSize: "13.5px",
    fontWeight: 600,
    color: text,
    minWidth: 0,
  },
  mbSessIcon: { width: "14px", height: "14px", color: textMut, flex: "none" },
  mbRight: { display: "flex", alignItems: "center", gap: "8px" },
  sseInd: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "11.5px",
    color: textMut,
    fontFamily: "var(--mono)",
    whiteSpace: "nowrap",
  },
  dot: { width: "8px", height: "8px", borderRadius: "50%", flex: "none" },
  // ghost 图标按钮（原型 .btn.btn-ghost.btn-icon；hover 态见 theme.css .icon-btn）
  iconBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    padding: 0,
    border: "none",
    borderRadius: "9px",
    background: "transparent",
    color: textSec,
    fontSize: "15px",
    lineHeight: 1,
    cursor: "pointer",
    flex: "none",
  },
  modelLabel: { fontSize: "12px", color: textSec },
  select: {
    background: surface,
    color: text,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "6px 8px",
    fontSize: "12px",
    outline: "none",
    maxWidth: "230px",
  },
  baseUrlTag: {
    fontSize: "11px",
    color: textMut,
    fontFamily: "monospace",
    padding: "3px 6px",
    border: `1px solid ${border}`,
    borderRadius: "6px",
  },
  reloadBtn: {
    marginLeft: "auto",
    padding: "6px 10px",
    border: `1px solid ${border}`,
    borderRadius: "8px",
    background: surface,
    color: textSec,
    fontSize: "12px",
    cursor: "pointer",
  },

  errorBanner: {
    padding: "12px 20px",
    background: "var(--red-soft)",
    borderBottom: "1px solid var(--red-border)",
    color: "var(--red)",
    fontSize: "13px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  // P1-4: amber warning banner shown while the SSE stream is down (distinct
  // from the red errorBanner — this is recoverable and auto-retries).
  sseDownBanner: {
    padding: "10px 20px",
    background: "var(--amber-soft)",
    borderBottom: "1px solid var(--amber-border)",
    color: "var(--amber)",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
  },
  errorClose: {
    background: "none",
    border: "none",
    color: "var(--red)",
    cursor: "pointer",
    fontSize: "18px",
  },
  welcome: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px",
    overflowY: "auto",
  },
  welcomeIcon: { fontSize: "64px", marginBottom: "16px" },
  welcomeTitle: { fontSize: "28px", fontWeight: 600, color: text, marginBottom: "8px" },
  welcomeText: { fontSize: "15px", color: textSec, marginBottom: "32px" },
  welcomeFeatures: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    maxWidth: "620px",
    marginBottom: "32px",
  },
  welcomeFeature: {
    display: "flex",
    gap: "12px",
    padding: "16px",
    background: surface,
    borderRadius: "12px",
    border: `1px solid ${border}`,
  },
  welcomeFeatureIcon: { fontSize: "24px" },
  welcomeFeatureTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: text,
    marginBottom: "4px",
  },
  welcomeFeatureDesc: { fontSize: "12px", color: textSec },
  welcomeBtn: {
    padding: "12px 32px",
    border: "none",
    borderRadius: "10px",
    background: accent,
    color: "#fff",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
  },
  welcomeStarting: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 32px",
    borderRadius: "10px",
    background: accentSoft,
    border: `1px solid ${border}`,
    color: accent,
    fontSize: "15px",
    fontWeight: 500,
  },
  welcomeSpinner: { fontSize: "18px" },
  // P1-4: de-emphasized "stage N/3 · waited Ns" hint inside the starting pill.
  welcomeProgress: {
    fontSize: "13px",
    fontWeight: 400,
    color: textSec,
  },
  noSession: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  noSessionIcon: { fontSize: "48px", marginBottom: "16px" },
  noSessionText: { fontSize: "14px", color: textSec, marginBottom: "16px" },
  newSessionLargeBtn: {
    padding: "10px 24px",
    border: "none",
    borderRadius: "10px",
    background: accent,
    color: "#fff",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  messagesArea: { flex: 1, overflowY: "auto", padding: "20px" },
  msgUser: { display: "flex", gap: "12px", marginBottom: "16px", justifyContent: "flex-end" },
  msgAssistant: { display: "flex", gap: "12px", marginBottom: "16px" },
  msgSystem: { display: "flex", justifyContent: "center", marginBottom: "12px" },
  systemNote: {
    fontSize: "11px",
    color: textSec,
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "999px",
    padding: "4px 12px",
  },
  msgAvatarUser: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: accent,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: 600,
    color: "#fff",
    order: 1,
    flexShrink: 0,
  },
  msgAvatarAssistant: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: surface,
    border: `1px solid ${border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    flexShrink: 0,
  },
  msgContent: { maxWidth: "76%", minWidth: 0 },
  msgRole: {
    fontSize: "11px",
    color: textMut,
    marginBottom: "4px",
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  modelTag: { color: accent, fontFamily: "monospace" },
  msgText: {
    fontSize: "14px",
    color: text,
    lineHeight: 1.6,
    background: surface,
    border: `1px solid ${border}`,
    padding: "12px 16px",
    borderRadius: "12px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  reasoningBox: {
    fontSize: "12px",
    color: textSec,
    lineHeight: 1.6,
    background: subtle,
    border: `1px dashed ${borderStrong}`,
    padding: "8px 12px",
    borderRadius: "10px",
    whiteSpace: "pre-wrap",
    marginBottom: "6px",
  },
  toolBox: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "6px",
    overflow: "hidden",
  },
  toolHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    fontSize: "12px",
    color: textSec,
    cursor: "pointer",
  },
  toolDot: (status: string): CSSProperties => ({
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    background: toolColors[status] || textMut,
    flexShrink: 0,
  }),
  toolName: { fontFamily: "monospace", color: text },
  toolStatus: { marginLeft: "auto", fontSize: "11px", color: textMut },
  toolBody: {
    padding: "8px 12px",
    borderTop: `1px solid ${border}`,
    fontSize: "11px",
    fontFamily: "monospace",
    color: textSec,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: "260px",
    overflowY: "auto",
    margin: 0,
    background: subtle,
  },
  turnError: {
    fontSize: "12px",
    color: "var(--red)",
    background: "var(--red-soft)",
    border: "1px solid var(--red-border)",
    padding: "8px 12px",
    borderRadius: "10px",
    marginTop: "6px",
    whiteSpace: "pre-wrap",
  },

  // --- patch part (live, on assistant turns) + turn diff review card -----
  patchBox: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: textSec,
    maxWidth: "100%",
  },
  patchFiles: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    color: text,
  },
  patchHash: {
    fontSize: "10px",
    color: textMut,
    fontFamily: "ui-monospace, monospace",
    flexShrink: 0,
  },
  diffCard: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginTop: "6px",
    overflow: "hidden",
    textAlign: "left" as const,
  },
  diffCardTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    padding: "8px 12px",
    fontSize: "12px",
    fontWeight: 600,
    color: text,
    background: subtle,
    borderBottom: `1px solid ${border}`,
  },
  diffStatAdd: { color: "var(--green)", fontFamily: "ui-monospace, monospace" },
  diffStatDel: { color: "var(--red)", fontFamily: "ui-monospace, monospace" },
  diffFileRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 12px",
    fontSize: "12px",
    cursor: "pointer",
    color: textSec,
  },
  diffFileStatus: (status: string): CSSProperties => {
    const map: Record<string, { background: string; color: string }> = {
      added: { background: "var(--green-soft)", color: "var(--green)" },
      modified: { background: "var(--primary-soft)", color: "var(--primary)" },
      deleted: { background: "var(--red-soft)", color: "var(--red)" },
      renamed: { background: "var(--indigo-soft)", color: "var(--indigo)" },
    };
    const s = map[status] || { background: subtle, color: textSec };
    return {
      fontSize: "10px",
      padding: "1px 6px",
      borderRadius: "6px",
      border: `1px solid ${border}`,
      flexShrink: 0,
      ...s,
    };
  },
  diffFileName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    color: text,
  },
  diffChevron: { fontSize: "10px", color: textMut, flexShrink: 0 },
  diffPatchBody: {
    margin: 0,
    padding: "6px 0",
    background: "var(--code-bg)",
    borderTop: `1px solid ${border}`,
    borderBottom: `1px solid ${border}`,
    fontFamily: "ui-monospace, monospace",
    fontSize: "11px",
    lineHeight: 1.6,
    maxHeight: "280px",
    overflowY: "auto",
  },
  diffLine: { padding: "0 12px", whiteSpace: "pre-wrap", wordBreak: "break-all" },
  diffLineAdd: { color: "var(--diff-add)", background: "var(--green-soft)" },
  diffLineDel: { color: "var(--diff-del)", background: "var(--red-soft)" },
  diffLineHunk: { color: accent, background: accentSoft },
  diffLineMeta: { color: textMut },
  diffActions: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "8px 12px",
    background: subtle,
  },
  revertBtn: {
    padding: "5px 12px",
    border: `1px solid var(--red)`,
    borderRadius: "6px",
    background: "transparent",
    color: "var(--red)",
    fontSize: "12px",
    cursor: "pointer",
  },
  unrevertBtn: {
    padding: "5px 12px",
    border: `1px solid ${accent}`,
    borderRadius: "6px",
    background: "transparent",
    color: accent,
    fontSize: "12px",
    cursor: "pointer",
  },
  revertedNote: { fontSize: "12px", color: "var(--green)" },

  // --- P1-2: protocol capability rendering --------------------------------
  // Session-level todo card (SSE `todo.updated`, not a message part).
  todoCard: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "10px",
    overflow: "hidden",
  },
  todoTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    fontSize: "12px",
    fontWeight: 600,
    color: text,
    background: subtle,
    borderBottom: `1px solid ${border}`,
  },
  todoItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "5px 12px",
    fontSize: "12px",
    color: textSec,
  },
  todoStatus: (status: string): CSSProperties => {
    const map: Record<string, { background: string; color: string }> = {
      pending: { background: subtle, color: textSec },
      in_progress: { background: accentSoft, color: accent },
      completed: { background: "var(--green-soft)", color: "var(--green)" },
      cancelled: { background: "var(--surface-3)", color: textMut },
    };
    const s = map[status] || map.pending;
    return {
      fontSize: "10px",
      padding: "1px 7px",
      borderRadius: "6px",
      border: `1px solid ${border}`,
      flexShrink: 0,
      minWidth: "52px",
      textAlign: "center" as const,
      ...s,
    };
  },
  todoContent: { flex: 1, minWidth: 0, lineHeight: 1.5 },
  todoDone: { textDecoration: "line-through", color: textMut },
  // Context-compaction marker part.
  compactionBox: {
    background: "var(--indigo-soft)",
    border: `1px solid var(--indigo-border)`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    color: "var(--indigo)",
  },
  // Subagent delegation part.
  subtaskBox: {
    background: surface,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    color: textSec,
  },
  subtaskAgent: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "6px",
    border: `1px solid ${border}`,
    background: accentSoft,
    color: accent,
    flexShrink: 0,
  },
  // Failed-and-retried attempt part.
  retryBox: {
    background: "var(--amber-soft)",
    border: `1px solid var(--amber-border)`,
    borderRadius: "10px",
    marginBottom: "6px",
    padding: "6px 12px",
    fontSize: "12px",
    color: "var(--amber)",
  },
  // File attachment part chip.
  fileChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    padding: "3px 10px",
    fontSize: "12px",
    color: textSec,
    marginBottom: "6px",
    maxWidth: "100%",
  },
  // Agent attribution marker chip.
  agentTagChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "11px",
    color: accent,
    background: accentSoft,
    borderRadius: "6px",
    padding: "1px 8px",
    marginBottom: "6px",
  },
  // Fork button on a user turn's role row.
  forkBtn: {
    marginLeft: "auto",
    border: "none",
    background: "transparent",
    color: textMut,
    cursor: "pointer",
    fontSize: "11px",
    padding: "1px 6px",
    borderRadius: "6px",
    flexShrink: 0,
  },
  // Regenerate button on the last assistant turn's role row.
  regenBtn: {
    marginLeft: "auto",
    border: "none",
    background: "transparent",
    color: textMut,
    cursor: "pointer",
    fontSize: "11px",
    padding: "1px 6px",
    borderRadius: "6px",
    flexShrink: 0,
  },
  turnMeta: { fontSize: "10px", color: textMut, marginTop: "4px" },
  streaming: { color: accent, fontSize: "11px" },
  cursor: { color: accent },
  // --- composer（对齐原型 .composer-wrap/.composer/.input-row 卡片化布局） ---
  inputArea: {
    flex: "none",
    borderTop: `1px solid ${border}`,
    background: surface,
  },
  composer: { maxWidth: "860px", width: "100%", margin: "0 auto", padding: "12px 20px 14px" },
  // 单卡片输入区（focus 描边见 theme.css .input-card:focus-within）
  inputRowCard: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "14px",
    padding: "6px 8px 7px",
  },
  promptChips: { display: "flex", flexWrap: "wrap", gap: "7px", padding: "4px 6px 2px" },
  inputBar: { display: "flex", alignItems: "center", gap: "8px", paddingTop: "5px" },
  inputTools: { display: "flex", gap: "3px" },
  inputCtx: { display: "flex", gap: "6px", minWidth: 0 },
  ibSpacer: { flex: 1 },
  inputHints: { display: "flex", gap: "8px", marginTop: "8px", fontSize: "11px", color: textMut },
  hintDot: { color: "var(--border-strong)" },
  attachBar: { display: "flex", flexWrap: "wrap", gap: "6px" },
  skillChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    height: "26px",
    padding: "0 10px",
    borderRadius: "999px",
    background: accentSoft,
    border: "1px solid var(--accent-border)",
    color: accent,
    fontSize: "12px",
    maxWidth: "240px",
  },
  attachChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    height: "26px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "var(--green-soft)",
    border: "1px solid rgba(52, 211, 153, 0.35)",
    color: "var(--green)",
    fontSize: "12px",
    maxWidth: "260px",
  },
  // chip 内文字省略（需要 span 包裹）
  chipText: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", minWidth: 0 },
  agentChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "12px",
    background: "var(--indigo-soft)",
    border: "1px solid var(--indigo-border)",
    color: "var(--indigo)",
    fontSize: "12px",
  },
  chipRemove: {
    border: "none",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    padding: 0,
    fontSize: "13px",
    lineHeight: 1,
    flex: "none",
  },
  // composer 底栏的上下文 chip 选择器（原型 .chip；hover 见 theme.css .ctx-chip）
  ctxChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    height: "26px",
    padding: "0 10px",
    borderRadius: "999px",
    fontSize: "12px",
    background: "transparent",
    border: `1px solid ${border}`,
    color: textSec,
    cursor: "pointer",
    whiteSpace: "nowrap",
    maxWidth: "220px",
    minWidth: 0,
  },
  // 存在"本条覆盖"时高亮（accent 色系）
  ctxChipActive: {
    background: accentSoft,
    borderColor: "var(--accent-border)",
    color: accent,
  },
  ctxChipArrow: { fontSize: "9px", color: textMut, flex: "none" },
  // 向上弹出的选择菜单（原型 .menu.ps-menu）
  psMenu: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    left: 0,
    minWidth: "230px",
    maxWidth: "320px",
    maxHeight: "300px",
    overflowY: "auto",
    padding: "6px",
    background: "var(--surface-2)",
    border: `1px solid ${borderStrong}`,
    borderRadius: "10px",
    boxShadow: "var(--shadow-2)",
    zIndex: 600,
  },
  psMenuTitle: { fontSize: "11px", color: textMut, padding: "6px 10px 4px", whiteSpace: "nowrap" },
  // hover 态见 theme.css .ps-menu-item
  psMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 10px",
    borderRadius: "7px",
    fontSize: "12.5px",
    color: textSec,
    cursor: "pointer",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  psMenuItemActive: { background: "var(--primary-soft)", color: text },
  psMenuDivider: { height: "1px", background: border, margin: "4px 2px" },
  psMenuAction: {
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "8px 10px",
    border: "none",
    borderRadius: "7px",
    background: "transparent",
    color: accent,
    fontSize: "12px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  skillPickerWrap: { position: "relative" },
  skillBackdrop: { position: "fixed", inset: 0, zIndex: 590 },
  skillMenu: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    left: 0,
    width: "320px",
    maxHeight: "300px",
    overflowY: "auto",
    background: "var(--surface-2)",
    border: `1px solid ${borderStrong}`,
    borderRadius: "10px",
    padding: "8px",
    zIndex: 600,
    boxShadow: "var(--shadow-2)",
  },
  skillMenuHeader: { fontSize: "12px", color: textSec, padding: "4px 6px 8px" },
  skillEmpty: { fontSize: "12px", color: textMut, padding: "8px 6px" },
  skillItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: text,
  },
  skillItemName: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  scopeProject: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(56,189,248,0.15)",
    color: "var(--scope-project)",
    border: "1px solid rgba(56,189,248,0.4)",
  },
  scopeGlobal: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(250,204,21,0.18)",
    color: "var(--scope-global)",
    border: "1px solid rgba(250,204,21,0.5)",
  },
  scopeBuiltin: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(167,139,250,0.15)",
    color: "var(--scope-user)",
    border: "1px solid rgba(167,139,250,0.4)",
  },
  skillMenuClose: {
    width: "100%",
    marginTop: "8px",
    padding: "6px",
    border: "none",
    borderRadius: "6px",
    background: accent,
    color: "#fff",
    fontSize: "12px",
    cursor: "pointer",
  },

  chatBody: { flex: 1, display: "flex", overflow: "hidden", minHeight: 0 },
  chatColumn: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", minWidth: 0 },

  // --- AI 润色提示条（输入区上方）-----------------------------------------
  polishBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "0 0 6px",
    padding: "4px 10px",
    borderRadius: "8px",
    background: accentSoft,
    border: `1px solid ${border}`,
    fontSize: "12px",
    color: textSec,
  },
  polishBarText: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  polishUndoBtn: {
    flex: "none",
    padding: "2px 10px",
    border: `1px solid ${borderStrong}`,
    borderRadius: "6px",
    background: surface,
    color: text,
    fontSize: "12px",
    cursor: "pointer",
  },
  // 润色进行中的图标按钮：与 disabled 的灰态区分开，表示「在跑」而非「不可点」
  iconBtnBusy: { color: accent, cursor: "progress" },

  // --- @-mention autocomplete (files + agents) ---------------------------
  atMenuWrap: { position: "relative", flex: 1, display: "flex" },
  atMenu: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    marginBottom: "6px",
    width: "min(480px, 60vw)",
    maxHeight: "260px",
    overflowY: "auto",
    background: "var(--surface-2)",
    border: `1px solid ${borderStrong}`,
    borderRadius: "10px",
    padding: "6px",
    zIndex: 600,
    boxShadow: "var(--shadow-2)",
  },
  atMenuHeader: { fontSize: "11px", color: textSec, padding: "4px 8px" },
  atItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: text,
  },
  atItemActive: {
    background: accentSoft,
  },
  atItemIcon: { flexShrink: 0 },
  atItemPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
  },
  atItemAgentName: {
    flexShrink: 0,
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: "var(--primary)",
    fontWeight: 600,
    minWidth: "80px",
  },
  atItemAgentDesc: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    color: textSec,
  },

  // --- Slash command menu (shares atMenu/atItem with @-mention) ----------
  cmdName: {
    flexShrink: 0,
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: text,
    minWidth: "80px",
  },
  cmdDesc: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    color: textSec,
  },
  cmdSource: {
    flexShrink: 0,
    fontSize: "10px",
    color: textSec,
    border: `1px solid ${border}`,
    borderRadius: "4px",
    padding: "1px 5px",
  },

  // --- Workspace file browser panel ---------------------------------------
  filesPanel: {
    width: "320px",
    flexShrink: 0,
    borderLeft: `1px solid ${border}`,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: surface,
  },
  filesPanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    // 窄面板下按钮换行而不是溢出裁切（全选/下载/删除/上传/刷新/关闭 六个）。
    flexWrap: "wrap",
    padding: "10px 12px",
    borderBottom: `1px solid ${border}`,
    fontSize: "13px",
    color: text,
    gap: "8px",
  },
  filesPanelBody: { flex: 1, overflowY: "auto", padding: "6px 4px" },
  wsUploadBtn: {
    border: `1px solid ${border}`,
    background: surface,
    color: text,
    cursor: "pointer",
    fontSize: "12px",
    borderRadius: "6px",
    padding: "3px 8px",
    flexShrink: 0,
  },
  // 删除是破坏性操作，用红色系与下载/上传区分开。
  wsDeleteBtn: {
    border: "1px solid var(--red-border)",
    background: "var(--red-soft)",
    color: "var(--red)",
    cursor: "pointer",
    fontSize: "12px",
    borderRadius: "6px",
    padding: "3px 8px",
    flexShrink: 0,
  },
  wsNotice: {
    padding: "6px 12px",
    fontSize: "12px",
    color: "var(--green)",
    background: "var(--green-soft)",
    borderBottom: `1px solid ${border}`,
  },
  // present_file 交付预览：文件面板顶部的多标签条 + 自动弹出开关。
  presentStrip: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 8px",
    borderBottom: `1px solid ${border}`,
    overflowX: "auto",
    background: subtle,
    flexShrink: 0,
  },
  presentTab: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    maxWidth: "160px",
    padding: "3px 8px",
    borderRadius: "6px",
    border: `1px solid ${border}`,
    background: surface,
    color: textSec,
    fontSize: "12px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  presentTabActive: {
    borderColor: accent,
    background: accentSoft,
    color: text,
  },
  presentTabLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  presentTabClose: {
    border: "none",
    background: "transparent",
    color: textMut,
    cursor: "pointer",
    fontSize: "12px",
    lineHeight: 1,
    padding: "0 2px",
    flexShrink: 0,
  },
  presentAutoBtn: {
    marginLeft: "auto",
    border: `1px solid ${border}`,
    background: surface,
    color: textMut,
    cursor: "pointer",
    fontSize: "11px",
    borderRadius: "6px",
    padding: "2px 6px",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  treeRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    color: textSec,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  treeRowHover: { color: text },
  treeFileSize: { marginLeft: "auto", fontSize: "11px", color: textMut, flexShrink: 0 },
  previewBack: {
    border: "none",
    background: "transparent",
    color: textSec,
    cursor: "pointer",
    fontSize: "12px",
    padding: "2px 4px",
  },
  previewBody: {
    flex: 1,
    overflowY: "auto",
    padding: "12px",
    fontSize: "13px",
    color: text,
    lineHeight: 1.6,
  },
  previewFrame: {
    width: "100%",
    height: "100%",
    border: "none",
    borderRadius: "8px",
    background: "#fff",
  },
  previewPre: {
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    color: text,
    background: subtle,
    padding: "10px",
    borderRadius: "8px",
  },
  previewImg: { maxWidth: "100%", borderRadius: "8px", display: "block", margin: "0 auto" },
  previewBinary: { color: textMut, padding: "24px 0", textAlign: "center" as const },
  // PPTX slide-outline preview (rendered from markitdown extraction; the
  // cards mimic a white 16:9 slide, so their text uses FIXED dark colors —
  // theme vars would render light-on-white in dark mode).
  pptxBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    paddingBottom: "10px",
    fontSize: "12px",
    color: textMut,
  },
  pptxSlides: { display: "flex", flexDirection: "column", gap: "14px" },
  pptxSlide: {
    position: "relative",
    aspectRatio: "16 / 9",
    background: "#ffffff",
    border: `1px solid ${border}`,
    borderRadius: "10px",
    overflow: "hidden",
    flexShrink: 0,
  },
  pptxSlideInner: {
    height: "100%",
    overflowY: "auto",
    padding: "5%",
  },
  pptxSlideNum: {
    position: "absolute",
    right: "10px",
    bottom: "8px",
    fontSize: "11px",
    color: "#9ca3af",
    background: "rgba(0,0,0,0.06)",
    borderRadius: "10px",
    padding: "1px 8px",
  },
  pptxSlideTitle: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#111827",
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: "6px",
    marginBottom: "6px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  pptxSlideLine: {
    fontSize: "13px",
    color: "#374151",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  pptxSlideTable: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "11px",
    color: "#4b5563",
    whiteSpace: "pre",
  },
  pptxPreviewShell: {
    height: "calc(100vh - 250px)",
    minHeight: "400px",
    display: "grid",
    gridTemplateColumns: "116px minmax(0, 1fr)",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: "10px",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    overflow: "hidden",
  },
  pptxThumbRail: {
    gridRow: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "10px 8px",
    overflowY: "auto",
    background: surface,
    borderRight: `1px solid ${border}`,
  },
  pptxThumb: {
    position: "relative",
    width: "100%",
    aspectRatio: "16 / 9",
    padding: 0,
    border: `1px solid ${border}`,
    borderRadius: "5px",
    overflow: "hidden",
    background: "#fff",
    cursor: "pointer",
    flexShrink: 0,
    color: "#6b7280",
    fontSize: "10px",
  },
  pptxThumbActive: { border: `2px solid ${accent}`, boxShadow: `0 0 0 1px ${accentSoft}` },
  pptxThumbViewer: { width: "100%", height: "100%", display: "block" },
  pptxStage: {
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "12px",
    overflow: "hidden",
    background: "#111827",
  },
  pptxFooter: {
    gridColumn: "1 / 3",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: "8px",
    minHeight: "44px",
    padding: "6px 10px",
    borderTop: `1px solid ${border}`,
    background: surface,
    color: textSec,
    fontSize: "12px",
  },
  pptxRenderHint: { color: textMut, padding: "24px 0", textAlign: "center" as const },
  pptxModeBtn: {
    flexShrink: 0,
    padding: "2px 10px",
    fontSize: "12px",
    cursor: "pointer",
    background: subtle,
    color: text,
    border: `1px solid ${border}`,
    borderRadius: "6px",
  },
  mdTitle: { fontSize: "16px", fontWeight: 700, color: text, margin: "12px 0 6px" },
  mdH2: { fontSize: "14px", fontWeight: 700, color: text, margin: "10px 0 4px" },
  mdP: { margin: "6px 0" },
  mdLi: { margin: "2px 0", paddingLeft: "8px", listStyle: "disc inside" as const },
  mdCode: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    background: "var(--code-bg)",
    padding: "1px 5px",
    borderRadius: "4px",
    color: "var(--code-accent)",
  },
  mdCodeBlock: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    background: "var(--code-bg)",
    border: "1px solid var(--code-border)",
    padding: "10px",
    borderRadius: "8px",
    overflowX: "auto",
    whiteSpace: "pre",
    margin: "8px 0",
    color: "var(--code-text)",
  },
  mdStrong: { color: text, fontWeight: 700 },
  // 卡片内 textarea：无独立边框，聚焦描边由 .input-card:focus-within 提供
  textInput: {
    flex: 1,
    padding: "9px 10px",
    border: "none",
    borderRadius: "8px",
    background: "transparent",
    color: text,
    fontSize: "14px",
    outline: "none",
    resize: "none",
    fontFamily: "inherit",
    lineHeight: 1.5,
    maxHeight: "180px",
  },
  // 发送 / 停止：34px 方形图标按钮（原型 .send-btn；交互态见 theme.css .send-btn）
  sendBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "34px",
    height: "34px",
    padding: 0,
    border: "none",
    borderRadius: "10px",
    background: accent,
    color: "#fff",
    fontSize: "16px",
    fontWeight: 700,
    lineHeight: 1,
    cursor: "pointer",
    flex: "none",
  },
  abortBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "34px",
    height: "34px",
    padding: 0,
    border: "none",
    borderRadius: "10px",
    background: "var(--red-fill)",
    color: "#fff",
    fontSize: "12px",
    lineHeight: 1,
    cursor: "pointer",
    flex: "none",
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: surface,
    borderRadius: "12px",
    width: "760px",
    maxWidth: "92vw",
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column",
    border: `1px solid ${border}`,
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    borderBottom: `1px solid ${border}`,
    fontSize: "15px",
    fontWeight: 600,
    color: text,
  },
  modalClose: {
    background: "none",
    border: "none",
    color: textSec,
    cursor: "pointer",
    fontSize: "20px",
  },
  modalBody: {
    padding: "16px",
    overflow: "auto",
    fontSize: "12px",
    fontFamily: "monospace",
    color: textSec,
    whiteSpace: "pre-wrap",
    margin: 0,
  },

  // --- fastk chunk 引用徽章 + 内容查看器 ---------------------------------
  // 徽章：行内可点击，展示知识库来源；中文文案，悬停有提示。
  chunkBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    padding: "0 8px",
    margin: "0 2px",
    height: "20px",
    borderRadius: "10px",
    background: accentSoft,
    border: `1px solid var(--primary-border)`,
    color: accent,
    fontSize: "12px",
    lineHeight: "18px",
    cursor: "pointer",
    verticalAlign: "baseline",
    whiteSpace: "nowrap",
    userSelect: "none",
  },
  chunkViewerBody: {
    padding: "16px",
    overflow: "auto",
    fontSize: "14px",
    color: text,
    lineHeight: 1.75,
    margin: 0,
    // 中文正文排版：中文优先字体栈；strict 禁则避免标点悬挂行首；
    // anywhere 兜底长 URL/英文词的断行。
    fontFamily:
      '-apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    lineBreak: "strict",
    overflowWrap: "anywhere",
  },
  chunkMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    padding: "10px 12px",
    marginBottom: "12px",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "8px",
    fontSize: "12px",
    color: textSec,
  },
  chunkMetaRow: { display: "flex", gap: "6px", alignItems: "baseline" },
  chunkMetaLabel: {
    flexShrink: 0,
    color: textMut,
    // 中文标签与西文路径混排时保持 12px 可读性
    fontSize: "12px",
  },
  chunkMetaValue: { color: text, fontFamily: "ui-monospace, monospace", wordBreak: "break-all" },
  chunkText: {
    whiteSpace: "pre-wrap",
    textAlign: "justify", // 中文两端对齐，避免右侧参差
  },
  chunkImage: {
    display: "block",
    maxWidth: "100%",
    marginTop: "12px",
    borderRadius: "8px",
    border: `1px solid ${border}`,
  },
  chunkImagePlaceholder: {
    display: "block",
    marginTop: "12px",
    padding: "28px 0",
    textAlign: "center",
    color: textMut,
    fontSize: "13px",
    border: `1px dashed ${border}`,
    borderRadius: "8px",
  },
  chunkImageError: {
    display: "block",
    marginTop: "12px",
    padding: "28px 0",
    textAlign: "center",
    color: "var(--red)",
    fontSize: "13px",
    border: "1px dashed var(--red-border)",
    borderRadius: "8px",
    background: "var(--red-soft)",
  },
  chunkLoading: {
    padding: "24px 0",
    textAlign: "center",
    color: textMut,
    fontSize: "13px",
  },
  chunkError: {
    padding: "16px",
    textAlign: "center",
    color: "var(--red)",
    background: "var(--red-soft)",
    border: "1px solid var(--red-border)",
    borderRadius: "8px",
    fontSize: "13px",
  },

  // --- PPTX 模板库选择器（composer 内向上弹出的画廊） ---------------------
  // 模板住在共享卷上、以只读挂载进容器，所以这里只挑选并注入容器内路径，
  // 从不下载字节到工作区。
  libPickerWrap: { position: "relative" },
  libMenu: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    left: 0,
    width: "min(660px, calc(100vw - 48px))",
    maxHeight: "440px",
    overflowY: "auto",
    background: "var(--surface-2)",
    border: `1px solid ${borderStrong}`,
    borderRadius: "12px",
    padding: "10px",
    zIndex: 600,
    boxShadow: "var(--shadow-2)",
  },
  libMenuHead: { display: "flex", alignItems: "baseline", gap: "8px", padding: "2px 4px 8px" },
  libMenuTitle: { fontSize: "12.5px", fontWeight: 600, color: text },
  libMenuHint: { fontSize: "11px", color: textMut, flex: 1, lineHeight: 1.5 },
  libSectionTitle: {
    fontSize: "11px",
    color: textMut,
    padding: "10px 4px 6px",
    letterSpacing: "0.3px",
  },
  libGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(176px, 1fr))",
    gap: "10px",
  },
  libCard: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "10px",
    cursor: "pointer",
    textAlign: "left",
    padding: 0,
    color: text,
  },
  libCardActive: { borderColor: "var(--accent-border)", boxShadow: `0 0 0 2px ${accentSoft}` },
  libThumbBox: {
    position: "relative",
    aspectRatio: "16 / 9",
    background: page,
    borderBottom: `1px solid ${border}`,
    overflow: "hidden",
  },
  libThumbImg: { display: "block", width: "100%", height: "100%", objectFit: "cover" },
  // 两段式缩略图的第一段：还没有真图时，用模板实际用色拼出色块占位
  libThumbSwatches: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    padding: "0 14px",
  },
  libSwatch: { flex: 1, height: "32px", maxWidth: "32px", borderRadius: "4px" },
  libThumbNote: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: "3px",
    textAlign: "center",
    fontSize: "10px",
    color: textMut,
  },
  libBadge: {
    position: "absolute",
    top: "5px",
    right: "5px",
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "rgba(0,0,0,0.55)",
    color: "#fff",
  },
  libCardBody: { padding: "7px 9px 9px", display: "flex", flexDirection: "column", gap: "4px" },
  libCardName: {
    fontSize: "12.5px",
    fontWeight: 600,
    color: text,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  libCardDesc: {
    fontSize: "11px",
    color: textSec,
    lineHeight: 1.5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  libCardMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px",
    alignItems: "center",
    fontSize: "10.5px",
    color: textMut,
  },
  libTag: {
    fontSize: "10px",
    padding: "1px 6px",
    borderRadius: "8px",
    background: "var(--surface-3)",
    border: `1px solid ${border}`,
    color: textSec,
  },
  // 调色板 / 风格配方条目（同一套卡片语言，只是没有缩略图）
  libMenuItem: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    padding: "8px 9px",
    borderRadius: "9px",
    border: `1px solid ${border}`,
    background: subtle,
    cursor: "pointer",
    textAlign: "left",
    color: text,
  },
  libMenuItemActive: { borderColor: "var(--accent-border)", background: accentSoft },
  libMenuName: { fontSize: "12px", fontWeight: 600, color: text },
  libMenuSub: { fontSize: "10.5px", color: textMut, lineHeight: 1.45 },
  libPaletteColors: { display: "flex", gap: "3px" },
  libPaletteDot: {
    width: "100%",
    height: "14px",
    borderRadius: "3px",
    border: `1px solid ${border}`,
  },
  libMenuClose: {
    width: "100%",
    marginTop: "10px",
    padding: "7px",
    border: "none",
    borderRadius: "7px",
    background: accent,
    color: "#fff",
    fontSize: "12px",
    cursor: "pointer",
  },
  libMenuEmpty: { fontSize: "12px", color: textMut, padding: "14px 6px", textAlign: "center" },
  libMenuError: { fontSize: "12px", color: "var(--red)", padding: "10px 6px", lineHeight: 1.6 },
  // 已选模板 / 调色板 / 配方在 promptChips 行的展示
  libChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    height: "26px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "var(--indigo-soft)",
    border: "1px solid var(--indigo-border)",
    color: "var(--indigo)",
    fontSize: "12px",
    maxWidth: "280px",
  },
  libChipSwatch: {
    width: "10px",
    height: "10px",
    borderRadius: "3px",
    flex: "none",
    border: `1px solid ${border}`,
  },

  // ---------------- 快捷技能（一键启用） ----------------
  // composer 内、输入卡片上方：按钮行 + 已启用技能标签行。
  // 配色沿用现有令牌，尺寸与 inputCard 的圆角/间距对齐，避免破坏对话框观感。
  skillQuickRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
    marginBottom: "8px",
  },
  skillQuickLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    color: textMut,
    marginRight: "2px",
  },
  quickSkillBtn: {
    borderRadius: "999px",
    fontSize: "12px",
    height: "26px",
    padding: "0 12px",
  },
  skillTagRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
    marginBottom: "8px",
  },
  skillTag: {
    margin: 0,
    fontSize: "12px",
    lineHeight: "22px",
    cursor: "pointer",
    userSelect: "none",
  },
  skillTagHint: {
    fontSize: "11px",
    color: textMut,
  },
  // 技能选择弹窗里的分组单选列表
  modalPickGroup: { marginBottom: "16px" },
  modalPickTitle: {
    fontSize: "12px",
    color: textSec,
    marginBottom: "8px",
    fontWeight: 600,
    letterSpacing: "0.02em",
  },
  modalRadioGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    maxHeight: "220px",
    overflowY: "auto",
    paddingRight: "6px",
  },
  modalRadio: {
    display: "flex",
    alignItems: "flex-start",
    fontSize: "13px",
    color: text,
    lineHeight: "20px",
  },
  modalRadioNote: {
    fontSize: "12px",
    color: textMut,
    marginLeft: "4px",
  },
  // 侧边栏快捷入口行（D12）：意见反馈 / 心愿墙，两个等宽按钮并排。
  // 放在「工作区」状态面板下方，与顶部 userInfo 行的管理员入口分区，
  // 避免普通用户能力与管理员能力挤在同一行造成权限语义混淆。
  quickActionsRow: {
    display: "flex",
    gap: "8px",
    padding: "0 14px 10px",
  },
  quickActionButton: {
    flex: 1,
    minWidth: 0,
    height: "32px",
    padding: "0 8px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    fontSize: "12px",
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    color: text,
    background: subtle,
    border: `1px solid ${border}`,
    borderRadius: "999px",
    cursor: "pointer",
    transition: "border-color var(--t), background var(--t), color var(--t)",
  },
};
